#ifndef TYPEPHP_OS_SYSCALL_H
#define TYPEPHP_OS_SYSCALL_H

/* Keep Linux x86_64 numbers only where both the operation and its ABI match.
 * Experimental TypePHP-OS operations live in a private range so they do not
 * occupy numbers that a future glibc port expects to have Linux semantics. */
enum typephp_os_syscall_number {
    TYPEPHP_SYS_READ = 0,
    TYPEPHP_SYS_WRITE = 1,
    TYPEPHP_SYS_CLOSE = 3,
    TYPEPHP_SYS_STAT = 4,
    TYPEPHP_SYS_FSTAT = 5,
    TYPEPHP_SYS_LSTAT = 6,
    TYPEPHP_SYS_LSEEK = 8,
    TYPEPHP_SYS_MMAP = 9,
    TYPEPHP_SYS_MPROTECT = 10,
    TYPEPHP_SYS_MUNMAP = 11,
    TYPEPHP_SYS_BRK = 12,
    TYPEPHP_SYS_IOCTL = 16,
    TYPEPHP_SYS_ACCESS = 21,
    TYPEPHP_SYS_GETPID = 39,
    TYPEPHP_SYS_EXIT = 60,
    TYPEPHP_SYS_UNAME = 63,
    TYPEPHP_SYS_FCNTL = 72,
    TYPEPHP_SYS_FSYNC = 74,
    TYPEPHP_SYS_FDATASYNC = 75,
    TYPEPHP_SYS_TRUNCATE = 76,
    TYPEPHP_SYS_FTRUNCATE = 77,
    TYPEPHP_SYS_GETCWD = 79,
    TYPEPHP_SYS_CHDIR = 80,
    TYPEPHP_SYS_MKDIR = 83,
    TYPEPHP_SYS_RMDIR = 84,
    TYPEPHP_SYS_UNLINK = 87,
    TYPEPHP_SYS_GETTIMEOFDAY = 96,
    TYPEPHP_SYS_GETUID = 102,
    TYPEPHP_SYS_GETGID = 104,
    TYPEPHP_SYS_GETEUID = 107,
    TYPEPHP_SYS_GETEGID = 108,
    TYPEPHP_SYS_GETPPID = 110,
    TYPEPHP_SYS_GETTID = 186,
    TYPEPHP_SYS_TIME = 201,
    TYPEPHP_SYS_GETDENTS64 = 217,
    TYPEPHP_SYS_CLOCK_GETTIME = 228,
    TYPEPHP_SYS_CLOCK_GETRES = 229,
    TYPEPHP_SYS_EXIT_GROUP = 231,
    TYPEPHP_SYS_OPENAT = 257,
    TYPEPHP_SYS_NEWFSTATAT = 262,
    TYPEPHP_SYS_FACCESSAT = 269,
    TYPEPHP_SYS_SPAWN = 0x54500001,
    TYPEPHP_SYS_RENAME = 0x54500003,
    TYPEPHP_SYS_MEMORY_INFO = 0x54500004,
};

#endif
